dist: trusty

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9


build:
  script:
    - export CC=gcc-9
    - export CXX=g++-9
    - cmake --version
    - cmake .
    - make

test:
  script:
    - ./alignment_tests