dist: trusty

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9

stages:
 - build
 - test

build:
  stage: build
  script:
    - export CC=gcc-9
    - export CXX=g++-9
    - cmake .
    - make

test:
  stage: test
  script
    - ./alignment_tests