sudo: required

language: cpp



matrix:
  # GCC 9, linux
  include: 
    - os: linux
      env: 
        - CC=gcc-9 
        - CXX=g++-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake

    # clang 8, linux, xenial
    - os: linux
      dist: xenial
      env:
        - CC=clang-8 
        - CXX=clang++-8
        - CXXFLAGS="-std=c++0x -stdlib=libc++"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - cmake

    # osx
    - os: osx
      osx_image: xcode11.2
      env:
        CC=clang
        CXX=clang++

script:
  - mkdir build
  - cd build

  - cmake .. 
  - cmake --build . --target all -- -j .. 

  # Run tests
  - cd test
  - ctest

notifications:
  email:
    false