dist: xenial
sudo: required

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages:
      - clang-8
      - libc++-8-dev
      - libc++abi-8-dev
      - cmake

script:

  - which clang-8
  
  - export CC=clang-8
  - export CXX=clang++-8

  - mkdir build
  - cd build

  - cmake .. 
  - cmake --build . --target all -- -j .. 

  - ctest